# Install Topmost Toolkit

In [ ]:
!pip install topmost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.6/89.6 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 53.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 34.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 766.7/766.7 MB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 32.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 35.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 19.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 10.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import os

DATA_FOLDER = "/content/drive/MyDrive/data"
DATASET_NAME = "Biomedical"

OUTPUT_FOLDER = os.path.join(DATA_FOLDER, f"{DATASET_NAME}Cluster")

# Preprocessing

In [5]:
raw_train_texts = []
train_labels = []
with open(os.path.join(DATA_FOLDER, "raw", f"{DATASET_NAME}.txt")) as fIn1:
    with open(os.path.join(DATA_FOLDER, "raw", f"{DATASET_NAME}_label.txt")) as fIn2:
            for text, label in zip(fIn1, fIn2):
                raw_train_texts.append(text.strip())
                train_labels.append(label.strip())

In [6]:
len(raw_train_texts)

19448

In [7]:
# preprocess raw data
from topmost.preprocessing import Preprocessing

preprocessing = Preprocessing(min_term=2, min_doc_count=3, min_length=0)

rst = preprocessing.preprocess(raw_train_texts=raw_train_texts,
                               train_labels=train_labels,
                               pretrained_WE=True)

preprocessing.save(OUTPUT_FOLDER, **rst)

2025-03-10 15:27:55,117 - TopMost - label2id: {'1': 0, '10': 1, '11': 2, '12': 3, '13': 4, '14': 5, '15': 6, '16': 7, '17': 8, '18': 9, '19': 10, '2': 11, '20': 12, '3': 13, '4': 14, '5': 15, '6': 16, '7': 17, '8': 18, '9': 19}
parsing texts: 100%|██████████| 19433/19433 [00:00<00:00, 62213.03it/s]
/usr/local/lib/python3.11/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning:

The parameter 'token_pattern' will not be used since 'tokenizer' is not None'

2025-03-10 15:27:56,079 - TopMost - Real vocab size: 3867
2025-03-10 15:27:56,083 - TopMost - Real training size: 19433 	 avg length: 7.430


[==================================================] 100.0% 252.1/252.1MB downloaded


loading word embeddings: 100%|██████████| 3867/3867 [00:02<00:00, 1340.73it/s]
2025-03-10 15:29:38,160 - TopMost - number of found embeddings: 3639/3867


In [8]:
# Replicate to test
import shutil

shutil.copyfile(src=os.path.join(DATA_FOLDER, "raw", f"{DATASET_NAME}.txt"),
                dst=os.path.join(OUTPUT_FOLDER, "train_raws.txt"))

shutil.copyfile(src=os.path.join(OUTPUT_FOLDER, "train_bow.npz"),
                dst=os.path.join(OUTPUT_FOLDER, "test_bow.npz"))

shutil.copyfile(src=os.path.join(OUTPUT_FOLDER, "train_labels.txt"),
                dst=os.path.join(OUTPUT_FOLDER, "test_labels.txt"))

shutil.copyfile(src=os.path.join(OUTPUT_FOLDER, "train_raws.txt"),
                dst=os.path.join(OUTPUT_FOLDER, "test_raws.txt"))

shutil.copyfile(src=os.path.join(OUTPUT_FOLDER, "train_texts.txt"),
                dst=os.path.join(OUTPUT_FOLDER, "test_texts.txt"))

'/content/drive/MyDrive/data/BiomedicalCluster/test_texts.txt'

# Embeddings

In [9]:
from topmost.data.basic_dataset import DocEmbedModel
# DEVICE = "cuda:0"
DEVICE = "cpu"

doc_embedder = DocEmbedModel(device=DEVICE, verbose=True)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:


The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.



modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [10]:
# Check thuộc tính của rst
rst.keys()

dict_keys(['vocab', 'train_bow', 'train_texts', 'train_labels', 'word_embeddings'])

In [11]:
len(rst['train_texts']), rst['train_texts'][0]

(19433, 'histochemical autoradiographic studies effects aging')

In [12]:
train_contextual_embed = doc_embedder.encode(rst['train_texts'])

Batches:   0%|          | 0/608 [00:00<?, ?it/s]

In [13]:
train_contextual_embed

array([[ 0.08053114,  0.05237199, -0.03804293, ..., -0.0208307 ,
         0.04260058, -0.02321726],
       [-0.073392  , -0.0899795 ,  0.02143211, ...,  0.01464676,
         0.12433223,  0.00134585],
       [ 0.10592757, -0.06309918, -0.01372996, ...,  0.00571864,
        -0.0395487 , -0.05391028],
       ...,
       [-0.05892688, -0.04529876, -0.04687954, ..., -0.04924601,
         0.09917276, -0.07777736],
       [-0.11773413, -0.02009332,  0.01388872, ...,  0.07371131,
        -0.01072125, -0.06803931],
       [-0.00612111,  0.00988563,  0.07561885, ...,  0.0080155 ,
        -0.03163801, -0.00390683]], dtype=float32)

In [14]:
# check ma trận train_contextual_embed
train_contextual_embed.shape

(19433, 384)

In [15]:
# check ma trận train_contextual_embed
train_contextual_embed[0]

array([ 8.05311427e-02,  5.23719937e-02, -3.80429327e-02,  3.99041660e-02,
       -1.03342917e-03,  1.92478113e-02,  4.99862805e-02,  9.41519812e-02,
       -8.19800794e-02,  4.15886939e-02, -6.74037216e-03, -2.45277919e-02,
        6.76516891e-02,  8.48277435e-02,  5.99290989e-03, -5.17513137e-03,
       -5.69829009e-02,  7.27552827e-03, -2.44011846e-03, -8.14419314e-02,
       -8.15805197e-02, -9.72222164e-03, -1.77306682e-02, -1.00930883e-02,
        1.75011419e-02, -3.92275751e-02, -2.79798917e-02, -4.67006750e-02,
       -9.11971480e-02,  2.92449445e-02,  1.32001881e-02,  4.01088782e-02,
        1.07821010e-01,  2.16386616e-02, -1.34751406e-02, -2.40079649e-02,
       -6.85794875e-02,  4.46656793e-02, -1.20848455e-01, -3.30451236e-04,
        2.13268003e-03, -6.48491085e-02, -3.05315107e-02,  2.62557026e-02,
        2.14635134e-02,  1.08209101e-03,  2.81963585e-04, -8.82234052e-02,
        4.29070257e-02,  7.86945224e-02, -1.50143690e-02, -8.21171552e-02,
        4.50865105e-02, -

In [16]:
from umap import UMAP
dim_rec_model = UMAP(n_neighbors=15, n_components=5, min_dist=0.0, metric='cosine', random_state=0)

In [17]:
train_contextual_embed = dim_rec_model.fit_transform(train_contextual_embed)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

/usr/local/lib/python3.11/dist-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.



In [18]:
train_contextual_embed.shape

(19433, 5)

In [141]:
from sklearn.cluster import KMeans
NUM_CLUSTERS = 50

kmeans = KMeans(n_clusters=NUM_CLUSTERS, random_state=0)
kmeans.fit(train_contextual_embed)
kmeans.labels_

array([15, 35, 35, ..., 40, 10, 23], dtype=int32)

In [142]:
pred_labels = kmeans.labels_.tolist()

In [143]:
labels = []
with open(os.path.join(OUTPUT_FOLDER, "train_labels.txt")) as fIn:
    for label in fIn:
        labels.append(int(label))

assert len(labels) == len(pred_labels)

In [144]:
import pandas as pd

pd.Series(labels).value_counts()

1     1000
9      992
11     991
18     988
3      987
4      986
8      985
14     983
0      982
10     978
2      977
15     977
12     976
16     974
19     964
17     963
13     943
7      940
5      932
6      915
Name: count, dtype: int64

In [145]:
pd.Series(pred_labels).value_counts()

2     1063
5      913
23     737
13     663
22     654
14     642
29     641
17     627
43     595
18     574
12     533
26     532
3      526
9      522
44     496
11     483
24     478
7      468
21     465
20     461
16     426
42     406
45     376
34     361
32     348
41     335
35     331
4      322
48     319
31     317
40     302
10     292
0      291
19     289
15     274
38     250
25     244
39     240
30     236
1      230
49     166
27     158
36     153
37     149
6      133
46     117
8       91
28      75
47      72
33      57
Name: count, dtype: int64

In [146]:
from topmost.evaluations.clustering import clustering_metric

clustering_metric(labels=labels,
                  preds=pred_labels)

{'Purity': 0.5325991869500335, 'NMI': 0.3986967384448245}

# Global Maps

In [150]:
import numpy as np

In [161]:
CLUSTER_FOLDER_NAME = "umap_globalcluster50"
os.makedirs(os.path.join(OUTPUT_FOLDER, CLUSTER_FOLDER_NAME), exist_ok=True)

In [162]:
with open(os.path.join(OUTPUT_FOLDER, CLUSTER_FOLDER_NAME, "global_maps.txt"), "w") as fOut:
    for label in pred_labels:
        fOut.write(str(label) + "\n")

In [163]:
# Read Vocab for Bow Global
vocab = []
with open(os.path.join(OUTPUT_FOLDER, "vocab.txt")) as fIn:
    for data in fIn:
        vocab.append(data.strip())

len(vocab)

3867

In [164]:
# nhóm và ghép nối tất cả văn bản theo nhãn, đồng thời đếm số lượng văn bản cho mỗi nhãn.
docs_dict = {}
docs_num = {}
for doc, label in zip(rst["train_texts"], pred_labels):
    if label not in docs_dict:
        docs_dict[label] = doc.strip()
        docs_num[label] = 1
    else:
        docs_dict[label] += " " + doc.strip()
        docs_num[label] += 1

In [165]:
docs_dict[0]

'signs ethanol tolerance physical dependence cat cyclic nucleotides spinal cells induced transformation myosin adenosine triphosphate pyrophosphate myosin isolation helical subunit heavy preparation adenosine pyrophosphate non enzymic method adenosine triphosphate arginine phosphotransferase lobster muscle molecular weight crystal molecular structure adenosine cyclic phosphate studies nature regulation purine nucleotides adenine phosphoribosyltransferase phosphoribosyltransferase ehrlich ascites tumour cells phosphorylation acids adenylate kinase adenosine triphosphate partial resolution adenosine template synthesis adenine nucleotides magnesium ions relation control mammalian cerebral cortex hexokinase interactions troponin troponin inhibition phosphofructokinase alpha tumor inhibitors mechanism activation adenosine cyclic monophosphate protein phosphokinase rabbit electron impact induced reactions methyl adenosine related methylation adenosine alkaline medium preparation properties m

In [166]:
docs_num[0]

291

In [167]:
# lấy tất cả các văn bản đã được gộp lại trong docs_dict và sắp xếp chúng theo thứ tự của nhãn, sau đó chỉ giữ lại phần văn bản (bỏ đi phần nhãn).
docs_concat_final = [u[1] for u in sorted(docs_dict.items(), key=lambda t: t[0])]
docs_concat_final

['signs ethanol tolerance physical dependence cat cyclic nucleotides spinal cells induced transformation myosin adenosine triphosphate pyrophosphate myosin isolation helical subunit heavy preparation adenosine pyrophosphate non enzymic method adenosine triphosphate arginine phosphotransferase lobster muscle molecular weight crystal molecular structure adenosine cyclic phosphate studies nature regulation purine nucleotides adenine phosphoribosyltransferase phosphoribosyltransferase ehrlich ascites tumour cells phosphorylation acids adenylate kinase adenosine triphosphate partial resolution adenosine template synthesis adenine nucleotides magnesium ions relation control mammalian cerebral cortex hexokinase interactions troponin troponin inhibition phosphofructokinase alpha tumor inhibitors mechanism activation adenosine cyclic monophosphate protein phosphokinase rabbit electron impact induced reactions methyl adenosine related methylation adenosine alkaline medium preparation properties 

In [168]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(vocabulary=vocab, tokenizer=lambda x: x.split())
bow = vectorizer.fit_transform(docs_concat_final)
bow

<50x3867 sparse matrix of type '<class 'numpy.int64'>'
	with 37927 stored elements in Compressed Sparse Row format>

In [169]:
bow = bow.toarray()
bow

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  1,  0],
       [ 1, 10,  2, ...,  0,  1,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  1, ...,  0,  1,  0],
       [ 3,  0,  0, ...,  0,  0,  0]])

In [170]:
import scipy.sparse

scipy.sparse.save_npz(os.path.join(OUTPUT_FOLDER, CLUSTER_FOLDER_NAME, "global_bow.npz"), scipy.sparse.csr_matrix(bow))